POST http://localhost:8080/login
Content-Type: application/json;charset=UTF-8


{
  "username" : "dongchul",
  "password" : 1234
}

###
//Role User Test Call
GET http://localhost:8080/
jwt-header:

###
// Refresh Test Call
GET http://localhost:8080/refresh
jwt-header:

###